### ISSUE TITLE
Invalid course code doesn't throw error

### ISSUE THREAD

**Issue by ramanxg** [icssc/peterportal-public-api#199]
When writing a query such as 
`grades(year:"2020-21", department:"COMPSCI", code:"999939999") `, this does not throw an error. There is an issue with the regex matching only a part of the string, so it thinks the code is valid, when it should throw an error.

**Comment by rgandhasri87** [comment]
This is really late, but I'd like to claim this one.

**Comment by rgandhasri87** [comment]
Has this issue been resolved already? The current regex matching string in grades.helper.ts is:
`^\d{5}$`
and I thought that should match the entire string. I also tested it in an online regex tester just to be sure and it seems to be working correctly (anything other than a 5 digit number sequence is not matched). Trying out a query on the PeterPortal GraphQL playground with a invalid course code (such 356600) also results in an error on there.

Perhaps I am not understanding the problem completely.

**Comment by ramanxg** [comment]
You're correct. seems like the issue was resolved already. You can take on another issue and don't worry about the due date.
